/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huatai_ficc_aurora_journal_proxy_ReaderNative */

#ifndef _Included_com_huatai_ficc_aurora_journal_proxy_ReaderNative
#define _Included_com_huatai_ficc_aurora_journal_proxy_ReaderNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    createReader
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_createReader
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    join
 * Signature: (JLjava/lang/String;Ljava/lang/String;JII)I
 */
JNIEXPORT jint JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_join
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong, jint, jint);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    disJoin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_disJoin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    dataAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_dataAvailable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    seekToTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_seekToTime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    currentFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_currentFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_ReaderNative
 * Method:    next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huatai_ficc_aurora_journal_proxy_ReaderNative_next
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
