/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huatai_ficc_aurora_journal_proxy_WriterNative */

#ifndef _Included_com_huatai_ficc_aurora_journal_proxy_WriterNative
#define _Included_com_huatai_ficc_aurora_journal_proxy_WriterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_WriterNative
 * Method:    createWriter
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_huatai_ficc_aurora_journal_proxy_WriterNative_createWriter
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jboolean);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_WriterNative
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huatai_ficc_aurora_journal_proxy_WriterNative_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_huatai_ficc_aurora_journal_proxy_WriterNative
 * Method:    writeBytesWithTime
 * Signature: (JJI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huatai_ficc_aurora_journal_proxy_WriterNative_writeBytesWithTime
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
